### PR TITLE
kelechi, working on the undernutrition aspect of our mapping

### PR DESCRIPTION
**Pull request by kelechichima13**
@naemiamanuel @RasikaBombatkar @marygouws @josemwaka55666 @AnitaMakori

### CODE REVIEW

**Review by ernestguevarra — COMMENTED** [review]
@kelechichima13 thanks for this PR.

As with your team's other PR, I will do a live formal review in class so that the rest of the class will see.

With regard to your confusion with the map and the merge approach you are using, your approach is correct and your comment that the map provided is wrong is partly correct.

The map is correct but the field you are using to merge doesn't have the same values in the map as in the dataset. I am refreshing the map data so that this will not be the case but will also demonstrate in class why this is an issue and what the best practice is for merging datasets.

**Comment by kelechichima13** [comment]
Thank you very much! The other members of my team are working on the different aspects of malnutrition for children and for the mother's dataset. We look forward to Monday!

**Review by naemiamanuel — APPROVED** [review]

**Review by naemiamanuel — APPROVED** [review]

**Review by josemwaka55666 — APPROVED** [review]
Good

**Comment by kelechichima13** [comment]
@RasikaBombatkar @naemiamanuel @josemwaka55666 @marygouws

**Comment by naemiamanuel** [comment]
Hi Ernest,
Regarding writing a report of the findings using R-markdown, do we need to create a README file for our group or...?

**Comment by ernestguevarra** [comment]
> Hi Ernest, Regarding writing a report of the findings using R-markdown, do we need to create a README file for our group or...?

There will be one Rmd report that all of you will write into. You will do that in the last session.

**Pull request merged**
