### PR TITLE
first steps of bottle neck analysis for team Naruto; KPIs

### PR DESCRIPTION
**Pull request by clicoselis**

### CODE REVIEW

**Review by ernestguevarra — APPROVED** [review]
@clicoselis and team @OxfordIHTM/naruto, this PR looks good. I like how you are processing the indicators.

I will approve this.

The one thing I want you to ensure is that you are also calculating at the state level (at least) and if you get the time, do it at locality level as well.

Right now, your code is only calculating at the national level.

**Comment by ernestguevarra** [comment]
Just a quick note to say that the errors in the automated checks is not with your code but with something else. So, don't worry about this error message from the automated checks. The checks on my local setup shows that code is running as expected.

**Comment by 9jagirlinoxford** [comment]
Okay, thank you @ernestguevarra  *We will calculate at the state level at least*

**Comment by clicoselis** [comment]
Hello Ernest, I noticed our code merged into main instead of the Naruto branch. Is that ok? Does that mean we need to build new branches from the main branch now?

**Pull request merged**
